//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSBIDE.Data.SQLDatabase.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class HashTags
    {
        public HashTags()
        {
            this.FeedPostHashtags = new HashSet<FeedPostHashtags>();
        }
    
        public int Id { get; set; }
        public string Content { get; set; }
    
        public virtual ICollection<FeedPostHashtags> FeedPostHashtags { get; set; }
    }
}
