//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSBIDE.Data.SQLDatabase.Edmx
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OsbideProcs : DbContext
    {
        public OsbideProcs()
            : base("name=OsbideProcs")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FeedPostHashtags> FeedPostHashtags { get; set; }
        public virtual DbSet<FeedPostUserTags> FeedPostUserTags { get; set; }
        public virtual DbSet<HashTags> HashTags { get; set; }
    
        public virtual ObjectResult<GetEventLogs_Result> GetActivityFeeds(Nullable<System.DateTime> dateReceivedMin, Nullable<System.DateTime> dateReceivedMax, string eventLogIds, string eventTypes, Nullable<int> courseId, Nullable<int> roleId, string commentFilter, string senderIds, Nullable<int> minLogId, Nullable<int> maxLogId, Nullable<int> offsetN, Nullable<int> topN)
        {
            var dateReceivedMinParameter = dateReceivedMin.HasValue ?
                new ObjectParameter("DateReceivedMin", dateReceivedMin) :
                new ObjectParameter("DateReceivedMin", typeof(System.DateTime));
    
            var dateReceivedMaxParameter = dateReceivedMax.HasValue ?
                new ObjectParameter("DateReceivedMax", dateReceivedMax) :
                new ObjectParameter("DateReceivedMax", typeof(System.DateTime));
    
            var eventLogIdsParameter = eventLogIds != null ?
                new ObjectParameter("EventLogIds", eventLogIds) :
                new ObjectParameter("EventLogIds", typeof(string));
    
            var eventTypesParameter = eventTypes != null ?
                new ObjectParameter("EventTypes", eventTypes) :
                new ObjectParameter("EventTypes", typeof(string));
    
            var courseIdParameter = courseId.HasValue ?
                new ObjectParameter("CourseId", courseId) :
                new ObjectParameter("CourseId", typeof(int));
    
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            var commentFilterParameter = commentFilter != null ?
                new ObjectParameter("CommentFilter", commentFilter) :
                new ObjectParameter("CommentFilter", typeof(string));
    
            var senderIdsParameter = senderIds != null ?
                new ObjectParameter("SenderIds", senderIds) :
                new ObjectParameter("SenderIds", typeof(string));
    
            var minLogIdParameter = minLogId.HasValue ?
                new ObjectParameter("MinLogId", minLogId) :
                new ObjectParameter("MinLogId", typeof(int));
    
            var maxLogIdParameter = maxLogId.HasValue ?
                new ObjectParameter("MaxLogId", maxLogId) :
                new ObjectParameter("MaxLogId", typeof(int));
    
            var offsetNParameter = offsetN.HasValue ?
                new ObjectParameter("OffsetN", offsetN) :
                new ObjectParameter("OffsetN", typeof(int));
    
            var topNParameter = topN.HasValue ?
                new ObjectParameter("TopN", topN) :
                new ObjectParameter("TopN", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEventLogs_Result>("GetActivityFeeds", dateReceivedMinParameter, dateReceivedMaxParameter, eventLogIdsParameter, eventTypesParameter, courseIdParameter, roleIdParameter, commentFilterParameter, senderIdsParameter, minLogIdParameter, maxLogIdParameter, offsetNParameter, topNParameter);
        }
    
        public virtual ObjectResult<GetRecentCompileErrors_Result> GetRecentCompileErrors(Nullable<int> senderId, Nullable<System.DateTime> timeframe)
        {
            var senderIdParameter = senderId.HasValue ?
                new ObjectParameter("SenderId", senderId) :
                new ObjectParameter("SenderId", typeof(int));
    
            var timeframeParameter = timeframe.HasValue ?
                new ObjectParameter("Timeframe", timeframe) :
                new ObjectParameter("Timeframe", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRecentCompileErrors_Result>("GetRecentCompileErrors", senderIdParameter, timeframeParameter);
        }
    
        public virtual ObjectResult<GetComments_Result> GetComments(string eventLogIds, Nullable<int> currentUserId)
        {
            var eventLogIdsParameter = eventLogIds != null ?
                new ObjectParameter("EventLogIds", eventLogIds) :
                new ObjectParameter("EventLogIds", typeof(string));
    
            var currentUserIdParameter = currentUserId.HasValue ?
                new ObjectParameter("CurrentUserId", currentUserId) :
                new ObjectParameter("CurrentUserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetComments_Result>("GetComments", eventLogIdsParameter, currentUserIdParameter);
        }
    
        public virtual ObjectResult<GetAgeLookup_Result> GetAgeLookup()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAgeLookup_Result>("GetAgeLookup");
        }
    
        public virtual ObjectResult<GetCourseLookup_Result> GetCourseLookup()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCourseLookup_Result>("GetCourseLookup");
        }
    
        public virtual ObjectResult<GetErrorQuotientErrorTypeData_Result> GetErrorQuotientErrorTypeData(string buildIds)
        {
            var buildIdsParameter = buildIds != null ?
                new ObjectParameter("buildIds", buildIds) :
                new ObjectParameter("buildIds", typeof(string));
            ((IObjectContextAdapter)this).ObjectContext.CommandTimeout = 60 * 60 * 24;
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetErrorQuotientErrorTypeData_Result>("GetErrorQuotientErrorTypeData", buildIdsParameter);
        }
    
        public virtual ObjectResult<GetErrorQuotientSessionData_Result> GetErrorQuotientSessionData(Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo, string userIds)
        {
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("dateFrom", dateFrom) :
                new ObjectParameter("dateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("dateTo", dateTo) :
                new ObjectParameter("dateTo", typeof(System.DateTime));
    
            var userIdsParameter = userIds != null ?
                new ObjectParameter("userIds", userIds) :
                new ObjectParameter("userIds", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetErrorQuotientSessionData_Result>("GetErrorQuotientSessionData", dateFromParameter, dateToParameter, userIdsParameter);
        }
    
        public virtual ObjectResult<GetProcedureData_Result> GetProcedureData(Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo, Nullable<int> studentId, string nameToken, Nullable<int> gender, Nullable<int> ageFrom, Nullable<int> ageTo, Nullable<int> courseId, string deliverable, Nullable<decimal> gradeFrom, Nullable<decimal> gradeTo)
        {
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("dateFrom", dateFrom) :
                new ObjectParameter("dateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("dateTo", dateTo) :
                new ObjectParameter("dateTo", typeof(System.DateTime));
    
            var studentIdParameter = studentId.HasValue ?
                new ObjectParameter("studentId", studentId) :
                new ObjectParameter("studentId", typeof(int));
    
            var nameTokenParameter = nameToken != null ?
                new ObjectParameter("nameToken", nameToken) :
                new ObjectParameter("nameToken", typeof(string));
    
            var genderParameter = gender.HasValue ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(int));
    
            var ageFromParameter = ageFrom.HasValue ?
                new ObjectParameter("ageFrom", ageFrom) :
                new ObjectParameter("ageFrom", typeof(int));
    
            var ageToParameter = ageTo.HasValue ?
                new ObjectParameter("ageTo", ageTo) :
                new ObjectParameter("ageTo", typeof(int));
    
            var courseIdParameter = courseId.HasValue ?
                new ObjectParameter("courseId", courseId) :
                new ObjectParameter("courseId", typeof(int));
    
            var deliverableParameter = deliverable != null ?
                new ObjectParameter("deliverable", deliverable) :
                new ObjectParameter("deliverable", typeof(string));
    
            var gradeFromParameter = gradeFrom.HasValue ?
                new ObjectParameter("gradeFrom", gradeFrom) :
                new ObjectParameter("gradeFrom", typeof(decimal));
    
            var gradeToParameter = gradeTo.HasValue ?
                new ObjectParameter("gradeTo", gradeTo) :
                new ObjectParameter("gradeTo", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProcedureData_Result>("GetProcedureData", dateFromParameter, dateToParameter, studentIdParameter, nameTokenParameter, genderParameter, ageFromParameter, ageToParameter, courseIdParameter, deliverableParameter, gradeFromParameter, gradeToParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> GetBuildDocUtilUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetBuildDocUtilUsers");
        }
    
        public virtual ObjectResult<GetBuildDocUtilBatch_Result> GetBuildDocUtilBatch(string userIds)
        {
            var userIdsParameter = userIds != null ?
                new ObjectParameter("UserIds", userIds) :
                new ObjectParameter("UserIds", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBuildDocUtilBatch_Result>("GetBuildDocUtilBatch", userIdsParameter);
        }
    
        public virtual ObjectResult<GetErrorQuotientDocumentData_Result> GetErrorQuotientDocumentData(string buildIds)
        {
            var buildIdsParameter = buildIds != null ?
                new ObjectParameter("buildIds", buildIds) :
                new ObjectParameter("buildIds", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetErrorQuotientDocumentData_Result>("GetErrorQuotientDocumentData", buildIdsParameter);
        }
    
        public virtual ObjectResult<GetErrorFixTimeStats_Result> GetErrorFixTimeStats()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetErrorFixTimeStats_Result>("GetErrorFixTimeStats");
        }
    
        public virtual ObjectResult<GetBuildErrorMessages_Result> GetBuildErrorMessages(string buildIds)
        {
            var buildIdsParameter = buildIds != null ?
                new ObjectParameter("buildIds", buildIds) :
                new ObjectParameter("buildIds", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBuildErrorMessages_Result>("GetBuildErrorMessages", buildIdsParameter);
        }
    
        public virtual ObjectResult<GetWatwinScoringErrorTypeData_Result> GetWatwinScoringErrorTypeData(string buildIds)
        {
            var buildIdsParameter = buildIds != null ?
                new ObjectParameter("buildIds", buildIds) :
                new ObjectParameter("buildIds", typeof(string));
            ((IObjectContextAdapter)this).ObjectContext.CommandTimeout = 60 * 60 * 24; // 1 day
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWatwinScoringErrorTypeData_Result>("GetWatwinScoringErrorTypeData", buildIdsParameter);
        }
    
        public virtual int InsertPostTags(Nullable<int> postId, string usertags, string hashtags)
        {
            var postIdParameter = postId.HasValue ?
                new ObjectParameter("postId", postId) :
                new ObjectParameter("postId", typeof(int));
    
            var usertagsParameter = usertags != null ?
                new ObjectParameter("usertags", usertags) :
                new ObjectParameter("usertags", typeof(string));
    
            var hashtagsParameter = hashtags != null ?
                new ObjectParameter("hashtags", hashtags) :
                new ObjectParameter("hashtags", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertPostTags", postIdParameter, usertagsParameter, hashtagsParameter);
        }
    
        public virtual ObjectResult<GetPassiveSocialEvents_Result> GetPassiveSocialEvents(Nullable<int> skip, Nullable<int> take)
        {
            var skipParameter = skip.HasValue ?
                new ObjectParameter("skip", skip) :
                new ObjectParameter("skip", typeof(int));
    
            var takeParameter = take.HasValue ?
                new ObjectParameter("take", take) :
                new ObjectParameter("take", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPassiveSocialEvents_Result>("GetPassiveSocialEvents", skipParameter, takeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> GetActionRequestsCount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetActionRequestsCount");
        }
    
        public virtual ObjectResult<Nullable<int>> GetPassiveSocialEventsCount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetPassiveSocialEventsCount");
        }
    
        public virtual ObjectResult<GetHashtags_Result> GetHashtags(string tag, Nullable<bool> ishandle)
        {
            var tagParameter = tag != null ?
                new ObjectParameter("tag", tag) :
                new ObjectParameter("tag", typeof(string));
    
            var ishandleParameter = ishandle.HasValue ?
                new ObjectParameter("ishandle", ishandle) :
                new ObjectParameter("ishandle", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHashtags_Result>("GetHashtags", tagParameter, ishandleParameter);
        }
    
        public virtual int MarkRead(Nullable<int> postId, Nullable<int> user, Nullable<bool> read)
        {
            var postIdParameter = postId.HasValue ?
                new ObjectParameter("PostId", postId) :
                new ObjectParameter("PostId", typeof(int));
    
            var userParameter = user.HasValue ?
                new ObjectParameter("User", user) :
                new ObjectParameter("User", typeof(int));
    
            var readParameter = read.HasValue ?
                new ObjectParameter("Read", read) :
                new ObjectParameter("Read", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MarkRead", postIdParameter, userParameter, readParameter);
        }
    
        public virtual ObjectResult<GetPassiveSocialEventProcessLog_Result> GetPassiveSocialEventProcessLog()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPassiveSocialEventProcessLog_Result>("GetPassiveSocialEventProcessLog");
        }
    
        public virtual int InsertPassiveSocialEventProcessLog(string tableName)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("tableName", tableName) :
                new ObjectParameter("tableName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertPassiveSocialEventProcessLog", tableNameParameter);
        }
    
        public virtual int UpdatePassiveSocialEventProcessLog(Nullable<int> id, string destTableName, Nullable<bool> completed, Nullable<int> processedRecordCounts)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var destTableNameParameter = destTableName != null ?
                new ObjectParameter("destTableName", destTableName) :
                new ObjectParameter("destTableName", typeof(string));
    
            var completedParameter = completed.HasValue ?
                new ObjectParameter("completed", completed) :
                new ObjectParameter("completed", typeof(bool));
    
            var processedRecordCountsParameter = processedRecordCounts.HasValue ?
                new ObjectParameter("processedRecordCounts", processedRecordCounts) :
                new ObjectParameter("processedRecordCounts", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdatePassiveSocialEventProcessLog", idParameter, destTableNameParameter, completedParameter, processedRecordCountsParameter);
        }
    
        public virtual ObjectResult<GetActiveSocialEventProcessInfo_Result> GetActiveSocialEventProcessInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetActiveSocialEventProcessInfo_Result>("GetActiveSocialEventProcessInfo");
        }
    
        public virtual ObjectResult<GetStateMachineEvents_Result> GetPrecalculatedStateMachineEvents(Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo, string studentIds)
        {
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("dateFrom", dateFrom) :
                new ObjectParameter("dateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("dateTo", dateTo) :
                new ObjectParameter("dateTo", typeof(System.DateTime));
    
            var studentIdsParameter = studentIds != null ?
                new ObjectParameter("studentIds", studentIds) :
                new ObjectParameter("studentIds", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStateMachineEvents_Result>("GetPrecalculatedStateMachineEvents", dateFromParameter, dateToParameter, studentIdsParameter);
        }
    
        public virtual ObjectResult<GetStateMachineEvents_Result> GetStateMachineEvents(Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo, string studentIds)
        {
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("dateFrom", dateFrom) :
                new ObjectParameter("dateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("dateTo", dateTo) :
                new ObjectParameter("dateTo", typeof(System.DateTime));
    
            var studentIdsParameter = studentIds != null ?
                new ObjectParameter("studentIds", studentIds) :
                new ObjectParameter("studentIds", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStateMachineEvents_Result>("GetStateMachineEvents", dateFromParameter, dateToParameter, studentIdsParameter);
        }
    
        public virtual ObjectResult<GetTrendsAndNotifications_Result> GetTrendsAndNotifications(Nullable<int> user, Nullable<int> num, Nullable<bool> getAll)
        {
            var userParameter = user.HasValue ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(int));
    
            var numParameter = num.HasValue ?
                new ObjectParameter("num", num) :
                new ObjectParameter("num", typeof(int));
    
            var getAllParameter = getAll.HasValue ?
                new ObjectParameter("getAll", getAll) :
                new ObjectParameter("getAll", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTrendsAndNotifications_Result>("GetTrendsAndNotifications", userParameter, numParameter, getAllParameter);
        }
    
        public virtual ObjectResult<string> GetDeliverableLookup(Nullable<int> courseId, Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo)
        {
            var courseIdParameter = courseId.HasValue ?
                new ObjectParameter("courseId", courseId) :
                new ObjectParameter("courseId", typeof(int));
    
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("dateFrom", dateFrom) :
                new ObjectParameter("dateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("dateTo", dateTo) :
                new ObjectParameter("dateTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetDeliverableLookup", courseIdParameter, dateFromParameter, dateToParameter);
        }
    
        public virtual ObjectResult<GetCalendarMeasuresByDay_Result> GetCalendarMeasuresByDay(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, string students, Nullable<int> courseId, string measures, Nullable<bool> isAvg)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            var studentsParameter = students != null ?
                new ObjectParameter("students", students) :
                new ObjectParameter("students", typeof(string));
    
            var courseIdParameter = courseId.HasValue ?
                new ObjectParameter("courseId", courseId) :
                new ObjectParameter("courseId", typeof(int));
    
            var measuresParameter = measures != null ?
                new ObjectParameter("measures", measures) :
                new ObjectParameter("measures", typeof(string));
    
            var isAvgParameter = isAvg.HasValue ?
                new ObjectParameter("isAvg", isAvg) :
                new ObjectParameter("isAvg", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCalendarMeasuresByDay_Result>("GetCalendarMeasuresByDay", startDateParameter, endDateParameter, studentsParameter, courseIdParameter, measuresParameter, isAvgParameter);
        }
    }
}
